package Quiz;
// importing packages we need for button 
import Appetizers.*;
import SeaFood.*;
import Dessert.*;
import SideDishes.*;
import Drinks.*;
/**
 *
 * @author Sajag
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        Milk = new javax.swing.JCheckBox();
        Gluten = new javax.swing.JCheckBox();
        panel2 = new java.awt.Panel();
        Appetizers = new javax.swing.JRadioButton();
        SeaFood = new javax.swing.JRadioButton();
        Desserts = new javax.swing.JRadioButton();
        SideDishes = new javax.swing.JRadioButton();
        Drinks = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Choose a category : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("any sensitivities?");

        Milk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Milk.setText("Milk");

        Gluten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Gluten.setText("Gluten");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gluten)
                    .addComponent(Milk))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Milk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gluten)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Appetizers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Appetizers.setText("Appetizers");
        Appetizers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppetizersActionPerformed(evt);
            }
        });

        SeaFood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SeaFood.setText("SeaFood");
        SeaFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaFoodActionPerformed(evt);
            }
        });

        Desserts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Desserts.setText("Desserts");
        Desserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertsActionPerformed(evt);
            }
        });

        SideDishes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SideDishes.setText("SideDishes");
        SideDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SideDishesActionPerformed(evt);
            }
        });

        Drinks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Drinks.setText("Drinks");
        Drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Appetizers)
                    .addComponent(SeaFood)
                    .addComponent(Desserts)
                    .addComponent(Drinks)
                    .addComponent(SideDishes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Appetizers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeaFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Desserts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SideDishes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Drinks)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel3.setText("a quick quiz!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AppetizersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppetizersActionPerformed
        // if statment to make the user choose one radio button only and not multiple at the same time
        if (Appetizers.isSelected()){
            SeaFood.setSelected(false);
            Drinks.setSelected(false);
            Desserts.setSelected(false);
            SideDishes.setSelected(false);
            
        }
    }//GEN-LAST:event_AppetizersActionPerformed

    private void DrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksActionPerformed
        // if statment to make the user choose one radio button only and not multiple at the same time
        if (Drinks.isSelected()){
            SeaFood.setSelected(false);
            Appetizers.setSelected(false);
            Desserts.setSelected(false);
            SideDishes.setSelected(false);
        }
    }//GEN-LAST:event_DrinksActionPerformed
    
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // main use :this button checks the options and everything the user chose and display the correct frame(recipe)
        
        // 2 booleans to check the sensitivity checkboxes
        boolean milkB = false;
        boolean glutenB = false;
        
        if(Milk.isSelected()){
            milkB = true;
        }
        if (Gluten.isSelected()){
            glutenB = true;
        }
        //Creating objects we'll need later
        Salad JFrameAP1 = new Salad();
        Hummus JFrameAP2 = new Hummus();
        Quesadillas JFrameAP3 = new Quesadillas();
        NoAnswer JFrameNothing = new NoAnswer();
        SalamonSauce JFrameSeaSauce = new SalamonSauce();
        SalamonBeans JFrameSeaBeans = new SalamonBeans();
        Tarts JFrameDessertTart = new Tarts();
        ChocolateMousse JFrameDessertChoco = new ChocolateMousse();
        Baklava JFrameDessertBaklava = new Baklava();
        Corn JFrameSideCorn = new Corn();
        SweetPotatos JFrameSidePotato = new SweetPotatos();
        Mocha JFrameDrinksMocha = new Mocha();
        Tea JFrameDrinksTea = new Tea();
        OrangeDrink JFrameDrinksOrange = new OrangeDrink();
        // checking what the user chose on radio buttons and then if they have any sensitivity
        // Appetizers radio button 
        if (Appetizers.isSelected()){
            if(milkB == true && glutenB == true){
                //show something without milk and gluten by just calling the object we created a bit before 
                JFrameAP1.show();
                }
            else if(milkB==false && glutenB==true){
                JFrameAP1.show();
            }
            else if(milkB==true && glutenB==false){
              JFrameAP2.show();
            }
            else{
                
                JFrameAP3.show();
            }                
    }//GEN-LAST:event_jButton1ActionPerformed
     // Sea food radio button
     else if(SeaFood.isSelected()){
         if(milkB==true && glutenB==true) {
         JFrameNothing.show();
         } 
         else if(milkB==true && glutenB==false){
         JFrameNothing.show();
         }
         else if (milkB==false && glutenB==true){
             JFrameSeaSauce.show();
         }
         else{
             JFrameSeaBeans.show();
         }
        }
     //Desserts radio button
     else if(Desserts.isSelected()){
     if(milkB==true && glutenB==true) {
         JFrameNothing.show();
         } 
         else if(milkB==true && glutenB==false){
         JFrameDessertTart.show();
         }
         else if (milkB==false && glutenB==true){
         JFrameDessertChoco.show();
         }
         else{
             JFrameDessertBaklava.show();
         }
     
     }
     //Side Dishes radio button
     else if(SideDishes.isSelected()){
     
     if(milkB==true && glutenB==true) {
         JFrameNothing.show();
         } 
         else if(milkB==true && glutenB==false){
         JFrameNothing.show();
         }
         else if (milkB==false && glutenB==true){
         JFrameSideCorn.show();
         }
         else{
             JFrameSidePotato.show();
         }
     }
    // Drinks radio button
     else{
    
    if(milkB==true && glutenB==true) {
         JFrameDrinksTea.show();
         } 
         else if(milkB==true && glutenB==false){
         JFrameDrinksMocha.show();
         }
         else if (milkB==false && glutenB==true){
         JFrameDrinksOrange.show();
         }
         else{
         JFrameDrinksTea.show();
         }
    }
     
        
     
   }
    
    
    private void SeaFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaFoodActionPerformed
        // if statment to make the user choose one radio button only and not multiple at the same time 
         if (SeaFood.isSelected()){
            Appetizers.setSelected(false);
            Drinks.setSelected(false);
            Desserts.setSelected(false);
            SideDishes.setSelected(false);

        }
    }//GEN-LAST:event_SeaFoodActionPerformed

    private void DessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertsActionPerformed
        // if statment to make the user choose one radio button only and not multiple at the same time
        if (Desserts.isSelected()){
            Appetizers.setSelected(false);
            Drinks.setSelected(false);
            SeaFood.setSelected(false);
            SideDishes.setSelected(false);

        }

    }//GEN-LAST:event_DessertsActionPerformed

    private void SideDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideDishesActionPerformed
        // if statment to make the user choose one radio button only and not multiple at the same time
        if (SideDishes.isSelected()){
            Appetizers.setSelected(false);
            Drinks.setSelected(false);
            SeaFood.setSelected(false);
            Desserts.setSelected(false);

        }
        
    }//GEN-LAST:event_SideDishesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Appetizers;
    private javax.swing.JRadioButton Desserts;
    private javax.swing.JRadioButton Drinks;
    private javax.swing.JCheckBox Gluten;
    private javax.swing.JCheckBox Milk;
    private javax.swing.JRadioButton SeaFood;
    private javax.swing.JRadioButton SideDishes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
